#undef METHOD_DECLARATIONS
#undef FIELD_DECLARATIONS
#undef FIELD_INIT
#undef FIELD_CPY
#undef FIELD_MOVE
#undef FIELD_CPY_ASSIGN
#undef FIELD_MOVE_ASSIGN
#undef METHOD_DEFINITIONS_IMPL
#undef METHOD_DEFINITIONS
#undef METHOD_DEFINITIONS_NI
#undef METHOD_DELEGATION_IMPL
#undef METHOD_DELEGATION
#undef METHOD_DELEGATION_NI

#undef SET_DEFINITION_IMPL
#undef MERGE_DEFINITION_IMPL
#undef DFLT_DEFINITION_IMPL
#undef MERGED_DEFINITION_IMPL
#undef SPECIFIC_DEFINITION_IMPL
#undef GET_DEFINITION_IMPL

#undef SET_DEFINITION
#undef MERGE_DEFINITION
#undef DFLT_DEFINITION
#undef MERGED_DEFINITION
#undef SPECIFIC_DEFINITION
#undef GET_DEFINITION

#undef SET_DEFINITION_NI
#undef MERGE_DEFINITION_NI
#undef DFLT_DEFINITION_NI
#undef MERGED_DEFINITION_NI
#undef SPECIFIC_DEFINITION_NI
#undef GET_DEFINITION_NI

#undef NOARG
#undef MERGE_VAR
#undef __conf_macros_hdr__h__
